### PR TITLE
Listen for and handle shutdownCompleted from RabbitMQ

### PR DESCRIPTION
**Pull request by christianekstrand**
If RabbitMQ goes down it sends a shutdownCompleted event to its channels. This pull requests handles this and makes sure that a graceful recovery is possible once it is back up again.

### CODE REVIEW

**Comment by jfarcand** [comment]
Thanks!!!

**Comment by christianekstrand** [comment]
Any chance this could get into RC5? :)

**Comment by jfarcand** [comment]
Sure will do this week for sure.

**Comment by christianekstrand** [comment]
Great, Thanks!

**Pull request merged**
