### PR TITLE
Fix for the superdev compilation failure

### PR DESCRIPTION
**Pull request by hegsie**

### CODE REVIEW

**Comment by jfarcand** [comment]
@hegsie Will this change works with GWT 2.6+?

**Comment by hegsie** [comment]
It turns out the GWT 2.6 requires the removal of all the RPC stuff that the extension uses and the removal of the above, I'll try and do another pull request to complete the required change today

**Comment by confile** [comment]
@hegsie Did you find a solution with works on GWT 2.6 and GWT 2.7?

**Comment by hegsie** [comment]
Sorry guys, I decided to stop using this and use plain javascript to interface with atmosphere, which is why I havent updated this.

**Pull request closed without merging**
